### ISSUE TITLE
Not possible to run on simulator

### ISSUE THREAD

**Issue by rene-dohan** [mesibo/messenger-app-android#12]
<img width="456" alt="screen shot 2019-02-08 at 10 21 34" src="https://user-images.githubusercontent.com/923610/52490858-55b6c280-2b8b-11e9-841b-b0423a98bbec.png">

I had to modify it in build script like this

```
  splits {
        abi {
            enable true
            reset()
            include 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'mips', 'mips64', 'arm64-v8a'
            universalApk true
        }
    }
```

but even after successfully run it fails at runtime like this:

```
02/08 10:26:09: Launching app
$ adb install-multiple -r -t /Users/renetik/Desktop/messenger-app-android/app/build/intermediates/resources/instant-run/debug/resources-x86-debug.apk /Users/renetik/Desktop/messenger-app-android/app/build/intermediates/split-apk/debug/dep/dependencies.apk /Users/renetik/Desktop/messenger-app-android/app/build/intermediates/split-apk/debug/slices/slice_2.apk /Users/renetik/Desktop/messenger-app-android/app/build/intermediates/split-apk/debug/slices/slice_1.apk /Users/renetik/Desktop/messenger-app-android/app/build/intermediates/split-apk/debug/slices/slice_0.apk /Users/renetik/Desktop/messenger-app-android/app/build/intermediates/split-apk/debug/slices/slice_3.apk /Users/renetik/Desktop/messenger-app-android/app/build/intermediates/split-apk/debug/slices/slice_5.apk /Users/renetik/Desktop/messenger-app-android/app/build/intermediates/split-apk/debug/slices/slice_6.apk /Users/renetik/Desktop/messenger-app-android/app/build/intermediates/split-apk/debug/slices/slice_4.apk /Users/renetik/Desktop/messenger-app-android/app/build/intermediates/split-apk/debug/slices/slice_7.apk /Users/renetik/Desktop/messenger-app-android/app/build/intermediates/split-apk/debug/slices/slice_9.apk /Users/renetik/Desktop/messenger-app-android/app/build/intermediates/split-apk/debug/slices/slice_8.apk /Users/renetik/Desktop/messenger-app-android/app/build/intermediates/instant-run-apk/debug/app-x86-debug.apk 
Split APKs installed in 12 s 577 ms
$ adb shell am start -n "org.mesibo.messenger/org.mesibo.messenger.StartUpActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: org.mesibo.messenger | org.mesibo.messenger.test
Waiting for application to come online: org.mesibo.messenger | org.mesibo.messenger.test
Waiting for application to come online: org.mesibo.messenger | org.mesibo.messenger.test
Waiting for application to come online: org.mesibo.messenger | org.mesibo.messenger.test
Waiting for application to come online: org.mesibo.messenger | org.mesibo.messenger.test
Waiting for application to come online: org.mesibo.messenger | org.mesibo.messenger.test
Waiting for application to come online: org.mesibo.messenger | org.mesibo.messenger.test
Waiting for application to come online: org.mesibo.messenger | org.mesibo.messenger.test
Waiting for application to come online: org.mesibo.messenger | org.mesibo.messenger.test
Waiting for application to come online: org.mesibo.messenger | org.mesibo.messenger.test
Waiting for application to come online: org.mesibo.messenger | org.mesibo.messenger.test
Waiting for application to come online: org.mesibo.messenger | org.mesibo.messenger.test
Waiting for application to come online: org.mesibo.messenger | org.mesibo.messenger.test
Waiting for application to come online: org.mesibo.messenger | org.mesibo.messenger.test
Connecting to org.mesibo.messenger
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/System.out: Debugger has connected
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/chatty: uid=10085(org.mesibo.messenger) identical 3 lines
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/chatty: uid=10085(org.mesibo.messenger) identical 1 line
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
Connected to the target VM, address: 'localhost:8611', transport: 'socket'
I/chatty: uid=10085(org.mesibo.messenger) identical 3 lines
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1484)
I/esibo.messenge: The ClassLoaderContext is a special shared library.
W/esibo.messenge: JIT profile information will not be recorded: profile file does not exits.
I/chatty: uid=10085(org.mesibo.messenger) identical 10 lines
W/esibo.messenge: JIT profile information will not be recorded: profile file does not exits.
I/InstantRun: starting instant run server: is main process
W/esibo.messenge: Verification of void com.facebook.FacebookSdk$1.<init>() took 111.736ms
E/esibo.messenge: No implementation found for void com.mesibo.api.JNIAPI.set_security(int) (tried Java_com_mesibo_api_JNIAPI_set_1security and Java_com_mesibo_api_JNIAPI_set_1security__I)
D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mesibo.messenger, PID: 6662
    java.lang.UnsatisfiedLinkError: No implementation found for void com.mesibo.api.JNIAPI.set_security(int) (tried Java_com_mesibo_api_JNIAPI_set_1security and Java_com_mesibo_api_JNIAPI_set_1security__I)
        at com.mesibo.api.JNIAPI.set_security(Native Method)
        at com.mesibo.api.Mesibo.setSecureConnection(SourceFile:1369)
        at org.mesibo.messenger.SampleAPI.init(SampleAPI.java:553)
        at org.mesibo.messenger.MainApplication.onCreate(MainApplication.java:66)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
E/esibo.messenge: No implementation found for long com.mesibo.api.JNIAPI.timestamp() (tried Java_com_mesibo_api_JNIAPI_timestamp and Java_com_mesibo_api_JNIAPI_timestamp__)
Disconnected from the target VM, address: 'localhost:8611', transport: 'socket'
```

**Comment by mesibo** [comment]
x86 devices not supported. Run it on arm* devices.

**Comment by rene-dohan** [comment]
So I can run it on arm simulator only ? Ok thanks I'll give it a try.

**Comment by rene-dohan** [comment]
Maybe you should write it down to readme for others, it's quite common to run x86 emulators for android these days.

**Comment by karan1213** [comment]
@mesibo 
I am getting these type of crashes on real devices as well on Crashlytics.

`Fatal Exception: java.lang.UnsatisfiedLinkError: Native method not found: com.mesibo.api.JNIAPI.set_security:(I)V
       at com.mesibo.api.JNIAPI.set_security(SourceFile)
       at com.mesibo.api.Mesibo.setSecureConnection(SourceFile:1369)
       at com.mypackage.Application.mesiboInit(Application.java:212)
       at com.mypackage.Application.onCreate(Application.java:100)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4684)
       at android.app.ActivityThread.access$1400(ActivityThread.java:159)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5419)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
       at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by FoamStudio** [comment]
Please is this error resolved cause I get this on real device after updating mesibo in my gradle

```
java.lang.UnsatisfiedLinkError: No implementation found for int com.mesibo.api.JNIAPI.get_connectionstatus() (tried Java_com_mesibo_api_JNIAPI_get_1connectionstatus and Java_com_mesibo_api_JNIAPI_get_1connectionstatus__)
        at com.mesibo.api.JNIAPI.get_connectionstatus(Native Method)
        at com.mesibo.api.Mesibo.getConnectionStatus(SourceFile:1313)
        at com.mesibo.api.Mesibo.c(SourceFile:3457)
        at com.mesibo.api.GenericReceiver.onReceive(SourceFile:16)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3040)
        at android.app.ActivityThread.-wrap18(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by mesibo** [comment]
Need more info. Which device ? Which Mesibo API version?
