### ISSUE TITLE
Error getting file from Downloads folder

### ISSUE THREAD

**Issue by danieltigse** [mesibo/messenger-app-android#14]
Device: Galaxy S8
OS: Android 8
Stacktrace:
```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=10005, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/raw:/storage/emulated/0/Download/invoice168314951.pdf flg=0x1 }} to activity {com.fomatmedical.febo/com.mesibo.messaging.MessagingActivity}: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/invoice168314951.pdf"
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4489)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4532)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/invoice168314951.pdf"
        at java.lang.Long.parseLong(Long.java:590)
        at java.lang.Long.valueOf(Long.java:804)
        at com.mesibo.mediapicker.e.a(SourceFile:296)
        at com.mesibo.mediapicker.MediaPicker.processOnActivityResult(SourceFile:1547)
        at com.mesibo.messaging.MessagingActivity.onActivityResult(MessagingActivity.java:1675)
        at android.app.Activity.dispatchActivityResult(Activity.java:7548)
```

Occurs when you chose a file from the Downloads section in the file picker

**Comment by mesibo** [comment]
Daniel, can you add steps to reproduce and we will look into it. 

Best

**Comment by danieltigse** [comment]
Sure.

1. Click on the plus icon
2. Click on the Clip Icon
3. Click on the left menu
4. Click on the `Downloads` section
5. Select any file from there
6. Crash

**Comment by mesibo** [comment]
We have fixed this issue in the latest release. Please gradle sync your project. Thanks for reporting it.

**Comment by mesibo** [comment]
I am closing this. Please reopen if you are still facing the issue!
