### ISSUE TITLE
Unable to test the app

### ISSUE THREAD

**Issue by transilience** [mesibo/messenger-app-android#58]
Cloned the repo,
added own google-services.json in the app folder

built the app using android studio, but sms authentication is not happening,

the sms for is not being received. neither are we able to use the demo phone numbers set in firebase console phone authentication

**Comment by transilience** [comment]
--------- beginning of crash
2020-11-13 07:06:48.498 5365-5365/org.mesibo.messenger E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mesibo.messenger, PID: 5365
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
        at org.mesibo.messenger.SampleAPI.parseResponse(SampleAPI.java:370)
        at org.mesibo.messenger.SampleAPI.access$200(SampleAPI.java:68)
        at org.mesibo.messenger.SampleAPI$ResponseHandler$1.run(SampleAPI.java:139)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2020-11-13 07:06:48.509 5365-5365/org.mesibo.messenger E/MesiboListeners: Mesibo_onCrash: org.mesibo.messenger.SampleAPI.parseResponse(SampleAPI.java:370)Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference


this is the crash we are getting when trying the google auth demo number

**Comment by mesibo** [comment]
Host backend API on your own server and use your own SMS OTP provider.
